USE sgv;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_completo VARCHAR(120) NOT NULL,
  matricula VARCHAR(8) NOT NULL,
  posto_graduacao VARCHAR(60) NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  perfil ENUM('ADMIN','EDITOR','LEITOR') NOT NULL,
  senha VARCHAR(60) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_usuarios_matricula (matricula),
  UNIQUE KEY uq_usuarios_cpf (cpf)
);
